# Basic continuous integration for firmware
#    Copyright 2024 Lea Calot
#
# @author Lea Calot
name: BuildFirmware
on:
  push:
    branches: [ ]
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install Python requirements
        run: |
          pip install -r requirements.txt
      - name: Perform firmware build
        run: |
          pio run
      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: FirmwareBinary
          path: ./.pio/build/*
          if-no-files-found: error